## Features Engineering
### Engineering Features
    :: Features Selection
    :: Features Encoding

In [78]:
import pandas as pd
import numpy as np

In [79]:
df = pd.read_csv("data_cleaned.csv")

In [80]:
df.head()

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,...,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes,Country
0,6317637,Le Petit Souffle,162,Makati City,"Third Floor, Century City Mall, Kalayaan Avenu...","Century City Mall, Poblacion, Makati City","Century City Mall, Poblacion, Makati City, Mak...",121.027535,14.565443,"French, Japanese, Desserts",...,Yes,No,No,No,3,4.8,Dark Green,Excellent,314,Phillipines
1,6304287,Izakaya Kikufuji,162,Makati City,"Little Tokyo, 2277 Chino Roces Avenue, Legaspi...","Little Tokyo, Legaspi Village, Makati City","Little Tokyo, Legaspi Village, Makati City, Ma...",121.014101,14.553708,Japanese,...,Yes,No,No,No,3,4.5,Dark Green,Excellent,591,Phillipines
2,6300002,Heat - Edsa Shangri-La,162,Mandaluyong City,"Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...","Edsa Shangri-La, Ortigas, Mandaluyong City","Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...",121.056831,14.581404,"Seafood, Asian, Filipino, Indian",...,Yes,No,No,No,4,4.4,Green,Very Good,270,Phillipines
3,6318506,Ooma,162,Mandaluyong City,"Third Floor, Mega Fashion Hall, SM Megamall, O...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.056475,14.585318,"Japanese, Sushi",...,No,No,No,No,4,4.9,Dark Green,Excellent,365,Phillipines
4,6314302,Sambo Kojin,162,Mandaluyong City,"Third Floor, Mega Atrium, SM Megamall, Ortigas...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.057508,14.584450,"Japanese, Korean",...,Yes,No,No,No,4,4.8,Dark Green,Excellent,229,Phillipines

From Exploration, Features such as country, city, Aggregate rating are most importance in predicting the If the resturant has online delivery or not.

In [81]:
df.columns

Index(['Restaurant ID', 'Restaurant Name', 'Country Code', 'City', 'Address',
       'Locality', 'Locality Verbose', 'Longitude', 'Latitude', 'Cuisines',
       'Average Cost for two', 'Currency', 'Has Table booking',
       'Has Online delivery', 'Is delivering now', 'Switch to order menu',
       'Price range', 'Aggregate rating', 'Rating color', 'Rating text',
       'Votes', 'Country'],
      dtype='object')

In [82]:
new_df = df[['City', 'Aggregate rating', 'Country', 'Has Online delivery']]

In [83]:
new_df = new_df.rename(columns={'Aggregate rating':'Aggregate_rating', 'Has Online delivery': 'Online_delivery'})

In [84]:
new_df.head()

               City  Aggregate_rating      Country Online_delivery
0       Makati City               4.8  Phillipines              No
1       Makati City               4.5  Phillipines              No
2  Mandaluyong City               4.4  Phillipines              No
3  Mandaluyong City               4.9  Phillipines              No
4  Mandaluyong City               4.8  Phillipines              No

In [85]:
new_df.dtypes

City                 object
Aggregate_rating    float64
Country              object
Online_delivery      object
dtype: object

In [101]:
new_city = []

for i in df["City"]:
    new_city.append(i[0:3])
new_city

['Mak',
 'Mak',
 'Man',
 'Man',
 'Man',
 'Man',
 'Pas',
 'Pas',
 'Pas',
 'Pas',
 'Pas',
 'Pas',
 'Que',
 'San',
 'San',
 'San',
 'San',
 'Tag',
 'Tag',
 'Tag',
 'Tag',
 'Tag',
 'Bra',
 'Bra',
 'Bra',
 'Bra',
 'Bra',
 'Bra',
 'Bra',
 'Bra',
 'Bra',
 'Bra',
 'Bra',
 'Bra',
 'Bra',
 'Bra',
 'Bra',
 'Bra',
 'Bra',
 'Bra',
 'Bra',
 'Bra',
 'Rio',
 'Rio',
 'Rio',
 'Rio',
 'Rio',
 'Rio',
 'Rio',
 'Rio',
 'Rio',
 'Rio',
 'Rio',
 'Rio',
 'Rio',
 'Rio',
 'Rio',
 'Rio',
 'Rio',
 'Rio',
 'Rio',
 'Rio',
 'Sí£',
 'Sí£',
 'Sí£',
 'Sí£',
 'Sí£',
 'Sí£',
 'Sí£',
 'Sí£',
 'Sí£',
 'Sí£',
 'Sí£',
 'Sí£',
 'Sí£',
 'Sí£',
 'Sí£',
 'Sí£',
 'Sí£',
 'Sí£',
 'Sí£',
 'Sí£',
 'Alb',
 'Alb',
 'Alb',
 'Alb',
 'Alb',
 'Alb',
 'Alb',
 'Alb',
 'Alb',
 'Alb',
 'Alb',
 'Alb',
 'Alb',
 'Alb',
 'Alb',
 'Alb',
 'Alb',
 'Alb',
 'Alb',
 'Alb',
 'Arm',
 'Ath',
 'Ath',
 'Ath',
 'Ath',
 'Ath',
 'Ath',
 'Ath',
 'Ath',
 'Ath',
 'Ath',
 'Ath',
 'Ath',
 'Ath',
 'Ath',
 'Ath',
 'Ath',
 'Ath',
 'Ath',
 'Ath',
 'Ath',
 'Aug',
 'Aug',
 'Aug',
 'Aug',
 'Aug',
 'Aug',
 'Aug',
 'Aug',
 'Aug',
 'Aug',
 'Aug',
 'Aug',
 'Aug',
 'Aug',
 'Aug',
 'Aug',
 'Aug',
 'Aug',
 'Aug',
 'Aug',
 'Bal',
 'Bee',
 'Boi',
 'Boi',
 'Boi',
 'Boi',
 'Boi',
 'Boi',
 'Boi',
 'Boi',
 'Boi',
 'Boi',
 'Boi',
 'Boi',
 'Boi',
 'Boi',
 'Boi',
 'Boi',
 'Boi',
 'Boi',
 'Boi',
 'Boi',
 'Ced',
 'Ced',
 'Ced',
 'Ced',
 'Ced',
 'Ced',
 'Ced',
 'Ced',
 'Ced',
 'Ced',
 'Ced',
 'Ced',
 'Ced',
 'Ced',
 'Ced',
 'Ced',
 'Ced',
 'Ced',
 'Ced',
 'Ced',
 'Cha',
 'Cla',
 'Coc',
 'Col',
 'Col',
 'Col',
 'Col',
 'Col',
 'Col',
 'Col',
 'Col',
 'Col',
 'Col',
 'Col',
 'Col',
 'Col',
 'Col',
 'Col',
 'Col',
 'Col',
 'Col',
 'Col',
 'Col',
 'Con',
 'Dal',
 'Dal',
 'Dal',
 'Dal',
 'Dal',
 'Dal',
 'Dal',
 'Dal',
 'Dal',
 'Dal',
 'Dal',
 'Dal',
 'Dal',
 'Dal',
 'Dal',
 'Dal',
 'Dal',
 'Dal',
 'Dal',
 'Dal',
 'Dav',
 'Dav',
 'Dav',
 'Dav',
 'Dav',
 'Dav',
 'Dav',
 'Dav',
 'Dav',
 'Dav',
 'Dav',
 'Dav',
 'Dav',
 'Dav',
 'Dav',
 'Dav',
 'Dav',
 'Dav',
 'Dav',
 'Dav',
 'Des',
 'Des',
 'Des',
 'Des',
 'Des',
 'Des',
 'Des',
 'Des',
 'Des',
 'Des',
 'Des',
 'Des',
 'Des',
 'Des',
 'Des',
 'Des',
 'Des',
 'Des',
 'Des',
 'Des',
 'Dic',
 'Dub',
 'Dub',
 'Dub',
 'Dub',
 'Dub',
 'Dub',
 'Dub',
 'Dub',
 'Dub',
 'Dub',
 'Dub',
 'Dub',
 'Dub',
 'Dub',
 'Dub',
 'Dub',
 'Dub',
 'Dub',
 'Dub',
 'Dub',
 'Eas',
 'Fer',
 'Fla',
 'For',
 'Gai',
 'Gai',
 'Gai',
 'Gai',
 'Gai',
 'Gai',
 'Gai',
 'Gai',
 'Gai',
 'Gai',
 'Gai',
 'Gai',
 'Gai',
 'Gai',
 'Gai',
 'Gai',
 'Gai',
 'Gai',
 'Gai',
 'Gai',
 'Hep',
 'Hep',
 'Hus',
 'Inv',
 'Lak',
 'Lak',
 'Lin',
 'Lor',
 'Mac',
 'Mac',
 'Mac',
 'Mac',
 'Mac',
 'Mac',
 'Mac',
 'Mac',
 'Mac',
 'Mac',
 'Mac',
 'Mac',
 'Mac',
 'Mac',
 'Mac',
 'Mac',
 'Mac',
 'Mac',
 'Mac',
 'Mac',
 'Mac',
 'May',
 'Mc ',
 'Mid',
 'Mil',
 'Mon',
 'Mon',
 'Ojo',
 'Orl',
 'Orl',
 'Orl',
 'Orl',
 'Orl',
 'Orl',
 'Orl',
 'Orl',
 'Orl',
 'Orl',
 'Orl',
 'Orl',
 'Orl',
 'Orl',
 'Orl',
 'Orl',
 'Orl',
 'Orl',
 'Orl',
 'Orl',
 'Pal',
 'Pay',
 'Pen',
 'Pen',
 'Pen',
 'Pen',
 'Pen',
 'Pen',
 'Pen',
 'Pen',
 'Pen',
 'Pen',
 'Pen',
 'Pen',
 'Pen',
 'Pen',
 'Pen',
 'Pen',
 'Pen',
 'Pen',
 'Pen',
 'Pen',
 'Pen',
 'Phi',
 'Poc',
 'Poc',
 'Poc',
 'Poc',
 'Poc',
 'Poc',
 'Poc',
 'Poc',
 'Poc',
 'Poc',
 'Poc',
 'Poc',
 'Poc',
 'Poc',
 'Poc',
 'Poc',
 'Poc',
 'Poc',
 'Poc',
 'Poc',
 'Pot',
 'Pri',
 'Res',
 'Res',
 'Res',
 'Res',
 'Res',
 'Res',
 'Res',
 'Res',
 'Res',
 'Res',
 'Res',
 'Res',
 'Res',
 'Res',
 'Res',
 'Res',
 'Res',
 'Res',
 'Res',
 'Res',
 'Sav',
 'Sav',
 'Sav',
 'Sav',
 'Sav',
 'Sav',
 'Sav',
 'Sav',
 'Sav',
 'Sav',
 'Sav',
 'Sav',
 'Sav',
 'Sav',
 'Sav',
 'Sav',
 'Sav',
 'Sav',
 'Sav',
 'Sav',
 'Sin',
 'Sin',
 'Sin',
 'Sin',
 'Sin',
 'Sin',
 'Sin',
 'Sin',
 'Sin',
 'Sin',
 'Sin',
 'Sin',
 'Sin',
 'Sin',
 'Sin',
 'Sin',
 'Sin',
 'Sin',
 'Sin',
 'Sin',
 'Sio',
 'Sio',
 'Sio',
 'Sio',
 'Sio',
 'Sio',
 'Sio',
 'Sio',
 'Sio',
 'Sio',
 'Sio',
 'Sio',
 'Sio',
 'Sio',
 'Sio',
 'Sio',
 'Sio',
 'Sio',
 'Sio',
 'Sio',
 'Tam',
 'Tam',
 'Tam',
 'Tam',
 'Tam',
 'Tam',
 'Tam',
 'Tam',
 'Tam',
 'Tam',
 'Tam',
 'Tam',
 'Tam',
 'Tam',
 'Tam',
 'Tam',
 'Tam',
 'Tam',
 'Tam',
 'Tam',
 'Tan',
 'Tre',
 'Val',
 'Val',
 'Val',
 'Val',
 'Val',
 'Val',
 'Val',
 'Val',
 'Val',
 'Val',
 'Val',
 'Val',
 'Val',
 'Val',
 'Val',
 'Val',
 'Val',
 'Val',
 'Val',
 'Val',
 'Ver',
 'Vic',
 'Vin',
 'Wat',
 'Wat',
 'Wat',
 'Wat',
 'Wat',
 'Wat',
 'Wat',
 'Wat',
 'Wat',
 'Wat',
 'Wat',
 'Wat',
 'Wat',
 'Wat',
 'Wat',
 'Wat',
 'Wat',
 'Wat',
 'Wat',
 'Wat',
 'Wei',
 'Win',
 'Yor',
 'Abu',
 'Abu',
 'Abu',
 'Abu',
 'Abu',
 'Abu',
 'Abu',
 'Abu',
 'Abu',
 'Abu',
 'Abu',
 'Abu',
 'Abu',
 'Abu',
 'Abu',
 'Abu',
 'Abu',
 'Abu',
 'Abu',
 'Abu',
 'Dub',
 'Dub',
 'Dub',
 'Dub',
 'Dub',
 'Dub',
 'Dub',
 'Dub',
 'Dub',
 'Dub',
 'Dub',
 'Dub',
 'Dub',
 'Dub',
 'Dub',
 'Dub',
 'Dub',
 'Dub',
 'Dub',
 'Dub',
 'Sha',
 'Sha',
 'Sha',
 'Sha',
 'Sha',
 'Sha',
 'Sha',
 'Sha',
 'Sha',
 'Sha',
 'Sha',
 'Sha',
 'Sha',
 'Sha',
 'Sha',
 'Sha',
 'Sha',
 'Sha',
 'Sha',
 'Sha',
 'Agr',
 'Agr',
 'Agr',
 'Agr',
 'Agr',
 'Agr',
 'Agr',
 'Agr',
 'Agr',
 'Agr',
 'Agr',
 'Agr',
 'Agr',
 'Agr',
 'Agr',
 'Agr',
 'Agr',
 'Agr',
 'Agr',
 'Agr',
 'Ahm',
 'Ahm',
 'Ahm',
 'Ahm',
 'Ahm',
 'Ahm',
 'Ahm',
 'Ahm',
 'Ahm',
 'Ahm',
 'Ahm',
 'Ahm',
 'Ahm',
 'Ahm',
 'Ahm',
 'Ahm',
 'Ahm',
 'Ahm',
 'Ahm',
 'Ahm',
 'Ahm',
 'All',
 'All',
 'All',
 'All',
 'All',
 'All',
 'All',
 'All',
 'All',
 'All',
 'All',
 'All',
 'All',
 'All',
 'All',
 'All',
 'All',
 'All',
 'All',
 'All',
 'Amr',
 'Amr',
 'Amr',
 'Amr',
 'Amr',
 'Amr',
 'Amr',
 'Amr',
 'Amr',
 'Amr',
 'Amr',
 'Amr',
 'Amr',
 'Amr',
 'Amr',
 'Amr',
 'Amr',
 'Amr',
 'Amr',
 'Amr',
 'Amr',
 'Aur',
 'Aur',
 'Aur',
 'Aur',
 'Aur',
 'Aur',
 'Aur',
 'Aur',
 'Aur',
 'Aur',
 'Aur',
 'Aur',
 'Aur',
 'Aur',
 'Aur',
 'Aur',
 'Aur',
 'Aur',
 'Aur',
 'Aur',
 'Ban',
 'Ban',
 'Ban',
 'Ban',
 'Ban',
 'Ban',
 'Ban',
 'Ban',
 'Ban',
 'Ban',
 'Ban',
 'Ban',
 'Ban',
 'Ban',
 'Ban',
 'Ban',
 'Ban',
 'Ban',
 'Ban',
 'Ban',
 'Bho',
 'Bho',
 'Bho',
 'Bho',
 'Bho',
 'Bho',
 'Bho',
 'Bho',
 'Bho',
 'Bho',
 'Bho',
 'Bho',
 'Bho',
 'Bho',
 'Bho',
 'Bho',
 'Bho',
 'Bho',
 'Bho',
 'Bho',
 'Bhu',
 'Bhu',
 'Bhu',
 'Bhu',
 'Bhu',
 'Bhu',
 'Bhu',
 'Bhu',
 'Bhu',
 'Bhu',
 'Bhu',
 'Bhu',
 'Bhu',
 'Bhu',
 'Bhu',
 'Bhu',
 'Bhu',
 'Bhu',
 'Bhu',
 'Bhu',
 'Bhu',
 'Cha',
 'Cha',
 'Cha',
 'Cha',
 'Cha',
 'Cha',
 'Cha',
 'Cha',
 'Cha',
 'Cha',
 'Cha',
 'Cha',
 'Cha',
 'Cha',
 'Cha',
 'Cha',
 'Cha',
 'Cha',
 'Che',
 'Che',
 'Che',
 'Che',
 'Che',
 'Che',
 'Che',
 'Che',
 'Che',
 'Che',
 'Che',
 'Che',
 'Che',
 'Che',
 'Che',
 'Che',
 'Che',
 'Che',
 'Che',
 'Che',
 'Coi',
 'Coi',
 'Coi',
 'Coi',
 'Coi',
 'Coi',
 'Coi',
 'Coi',
 'Coi',
 'Coi',
 'Coi',
 'Coi',
 'Coi',
 'Coi',
 'Coi',
 'Coi',
 'Coi',
 'Coi',
 'Coi',
 'Coi',
 'Deh',
 'Deh',
 'Deh',
 'Deh',
 'Deh',
 'Deh',
 'Deh',
 'Deh',
 'Deh',
 'Deh',
 'Deh',
 'Deh',
 'Deh',
 'Deh',
 'Deh',
 'Deh',
 'Deh',
 'Deh',
 'Deh',
 'Deh',
 'Far',
 'Far',
 'Far',
 'Far',
 'Far',
 'Far',
 'Far',
 'Far',
 'Far',
 'Far',
 'Far',
 'Far',
 'Far',
 'Far',
 'Far',
 'Far',
 'Far',
 'Far',
 'Far',
 'Far',
 'Far',
 'Far',
 'Far',
 'Far',
 'Far',
 'Far',
 'Far',
 'Far',
 'Far',
 'Far',
 'Far',
 'Far',
 'Far',
 'Far',
 'Far',
 'Far',
 'Far',
 'Far',
 'Far',
 'Far',
 'Far',
 'Far',
 'Far',
 'Far',
 'Far',
 'Far',
 'Far',
 'Far',
 'Far',
 'Far',
 'Far',
 'Far',
 'Far',
 'Far',
 'Far',
 'Far',
 'Far',
 'Far',
 'Far',
 'Far',
 'Far',
 'Far',
 'Far',
 'Far',
 'Far',
 'Far',
 'Far',
 'Far',
 'Far',
 'Far',
 'Far',
 'Far',
 'Far',
 'Far',
 'Far',
 'Far',
 'Far',
 'Far',
 'Far',
 'Far',
 'Far',
 'Far',
 'Far',
 'Far',
 'Far',
 'Far',
 'Far',
 'Far',
 'Far',
 'Far',
 'Far',
 'Far',
 'Far',
 'Far',
 'Far',
 'Far',
 'Far',
 'Far',
 'Far',
 'Far',
 'Far',
 'Far',
 'Far',
 'Far',
 'Far',
 'Far',
 'Far',
 'Far',
 'Far',
 'Far',
 'Far',
 'Far',
 'Far',
 'Far',
 'Far',
 'Far',
 'Far',
 'Far',
 'Far',
 'Far',
 'Far',
 'Far',
 'Far',
 'Far',
 'Far',
 'Far',
 'Far',
 'Far',
 'Far',
 'Far',
 'Far',
 'Far',
 'Far',
 'Far',
 'Far',
 ...]

In [87]:
len(new_city)

9551

In [103]:
new_city = pd.Series(new_city)

new_df.City = new_city


## removing rare values
temp_df = pd.Series(new_df['City'].value_counts())
temp_df[temp_df >= 0.1].index

Index(['New', 'Gur', 'Noi', 'Far', 'Man', 'Col', 'Dub', 'Gha', 'Bhu', 'Ban',
       ...
       'Pot', 'Phi', 'Pay', 'Pal', 'Ojo', 'Pan', 'Mil', 'Mid', 'Mc ', 'Vic'],
      dtype='object', length=125)

In [104]:
# let's create a dictionary to replace the rare labels with the
# string 'rare'

city_dict = {
    k: ('rare' if k not in temp_df[temp_df >= 0.2].index else k)
    for k in temp_df.index
}

city_dict

{'New': 'New',
 'Gur': 'Gur',
 'Noi': 'Noi',
 'Far': 'Far',
 'Man': 'Man',
 'Col': 'Col',
 'Dub': 'Dub',
 'Gha': 'Gha',
 'Bhu': 'Bhu',
 'Ban': 'Ban',
 'Amr': 'Amr',
 'Ahm': 'Ahm',
 'Luc': 'Luc',
 'Pen': 'Pen',
 'Ran': 'Ran',
 'Mac': 'Mac',
 'Guw': 'Guw',
 'Mum': 'Mum',
 'Nas': 'Nas',
 'Ath': 'Ath',
 'Mys': 'Mys',
 'Poc': 'Poc',
 'Cap': 'Cap',
 'Lud': 'Lud',
 'Res': 'Res',
 'Sav': 'Sav',
 'Sin': 'Sin',
 'Sio': 'Sio',
 'Tam': 'Tam',
 'Bra': 'Bra',
 'Pre': 'Pre',
 'Val': 'Val',
 'Kol': 'Kol',
 'Alb': 'Alb',
 'Koc': 'Koc',
 'Wat': 'Wat',
 'Kan': 'Kan',
 'Jai': 'Jai',
 'Ind': 'Ind',
 'Abu': 'Abu',
 'Sha': 'Sha',
 'Agr': 'Agr',
 'Sí£': 'Sí£',
 'All': 'All',
 'Nag': 'Nag',
 'Orl': 'Orl',
 'Aur': 'Aur',
 'Aug': 'Aug',
 'Doh': 'Doh',
 'Ced': 'Ced',
 'Lon': 'Lon',
 'Dal': 'Dal',
 'Dav': 'Dav',
 'Des': 'Des',
 'Edi': 'Edi',
 'Boi': 'Boi',
 'Bir': 'Bir',
 'Wel': 'Wel',
 'Auc': 'Auc',
 'Goa': 'Goa',
 'Gai': 'Gai',
 'Ank': 'Ank',
 'Viz': 'Viz',
 'Var': 'Var',
 'Vad': 'Vad',
 'Sur': 'Sur',
 'Deh': 'Deh',
 'Coi': 'Coi',
 'Che': 'Che',
 'Pun': 'Pun',
 'Pud': 'Pud',
 'Pat': 'Pat',
 'Bho': 'Bho',
 'Rio': 'Rio',
 'Cha': 'Cha',
 'Hyd': 'Hyd',
 'Jak': 'Jak',
 'San': 'San',
 'ÛÁs': 'ÛÁs',
 'Joh': 'Joh',
 'Pas': 'Pas',
 'Tag': 'Tag',
 'Tan': 'Tan',
 'Inn': 'Inn',
 'Sec': 'Sec',
 'Bog': 'Bog',
 'Mak': 'Mak',
 'Lak': 'Lak',
 'Hep': 'Hep',
 'Mon': 'Mon',
 'Eas': 'Eas',
 'Inv': 'Inv',
 'Hus': 'Hus',
 'For': 'For',
 'Fla': 'Fla',
 'Fer': 'Fer',
 'Yor': 'Yor',
 'Lin': 'Lin',
 'Con': 'Con',
 'Coc': 'Coc',
 'Cla': 'Cla',
 'Bee': 'Bee',
 'Bal': 'Bal',
 'Arm': 'Arm',
 'Que': 'Que',
 'Dic': 'Dic',
 'Lor': 'Lor',
 'Win': 'Win',
 'May': 'May',
 'Wei': 'Wei',
 'Vin': 'Vin',
 'Ver': 'Ver',
 'Tre': 'Tre',
 'Pri': 'Pri',
 'Moh': 'Moh',
 'Pot': 'Pot',
 'Phi': 'Phi',
 'Pay': 'Pay',
 'Pal': 'Pal',
 'Ojo': 'Ojo',
 'Pan': 'Pan',
 'Mil': 'Mil',
 'Mid': 'Mid',
 'Mc ': 'Mc ',
 'Vic': 'Vic'}

In [105]:
city_grouped = new_df['City'].map(city_dict)

In [106]:
dum = pd.get_dummies(city_grouped)
dum

,Abu,Agr,Ahm,Alb,All,Amr,Ank,Arm,Ath,Auc,...,Ver,Vic,Vin,Viz,Wat,Wei,Wel,Win,Yor,ÛÁs
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9546,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
9547,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
9548,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
9549,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
9550,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

In [107]:
data_new = pd.concat([new_df, dum], axis=1)

In [108]:
data_new

,City,Aggregate_rating,Country,Online_delivery,Abu,Agr,Ahm,Alb,All,Amr,...,Ver,Vic,Vin,Viz,Wat,Wei,Wel,Win,Yor,ÛÁs
0,Mak,4.8,Phillipines,No,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,Mak,4.5,Phillipines,No,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,Man,4.4,Phillipines,No,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,Man,4.9,Phillipines,No,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,Man,4.8,Phillipines,No,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9546,ÛÁs,4.1,Turkey,No,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
9547,ÛÁs,4.2,Turkey,No,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
9548,ÛÁs,3.7,Turkey,No,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
9549,ÛÁs,4.0,Turkey,No,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
9550,ÛÁs,4.0,Turkey,No,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

In [109]:
data_new.drop("City", axis=1, inplace=True)

In [110]:
# dum = pd.get_dummies(data_new['Online_delivery'])
# dum

In [111]:
# data_new = pd.concat([data_new, dum], axis=1)
# data_new.drop("Online_delivery", axis=1, inplace=True)

In [112]:
data_new

,Aggregate_rating,Country,Online_delivery,Abu,Agr,Ahm,Alb,All,Amr,Ank,...,Ver,Vic,Vin,Viz,Wat,Wei,Wel,Win,Yor,ÛÁs
0,4.8,Phillipines,No,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,4.5,Phillipines,No,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,4.4,Phillipines,No,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,4.9,Phillipines,No,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,4.8,Phillipines,No,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9546,4.1,Turkey,No,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
9547,4.2,Turkey,No,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
9548,3.7,Turkey,No,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
9549,4.0,Turkey,No,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
9550,4.0,Turkey,No,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

In [113]:
dum = pd.get_dummies(data_new['Country'])

In [114]:
data_new = pd.concat([data_new, dum], axis=1)
data_new.drop("Country", axis=1, inplace=True)

In [115]:
data_new

,Aggregate_rating,Online_delivery,Abu,Agr,Ahm,Alb,All,Amr,Ank,Arm,...,New Zealand,Phillipines,Qatar,Singapore,South Africa,Sri Lanka,Turkey,UAE,United Kingdom,United States
0,4.8,No,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
1,4.5,No,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
2,4.4,No,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
3,4.9,No,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
4,4.8,No,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9546,4.1,No,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
9547,4.2,No,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
9548,3.7,No,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
9549,4.0,No,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
9550,4.0,No,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0

In [122]:
data_new['Online_delivery'] = data_new['Online_delivery'].replace({'No': 0, 'Yes': 1})

In [127]:
data_new.dtypes

Aggregate_rating    float64
Online_delivery       int64
Abu                   uint8
Agr                   uint8
Ahm                   uint8
                     ...
Sri Lanka             uint8
Turkey                uint8
UAE                   uint8
United Kingdom        uint8
United States         uint8
Length: 142, dtype: object

In [128]:
data_new.to_csv(r"C:\Users\HP\Documents\Data Science\EDA\zomato\data_prepared.csv",index = False)